### ISSUE TITLE
Question: When I add textboxes or any of the form fields into the PDF, Is there a way to make those fields intractable?

### ISSUE THREAD

**Issue by ashishjaddu** [SimplePDF/simplepdf-embed#9]
Firstly I would like to appreciate your effort on this! It is wonderful to see such resources as a developer.
Currently When i add text boxes to the PDF and add text into those fields it works well but I want to make those added fields as intractable. If i open with another PDF reader I must be able to edit those added text box feilds as in similar to the fillable PDF concept.

**Comment by bendersej** [comment]
Hey @ashishjaddu!

> If i open with another PDF reader I must be able to edit those added text box feilds as in similar to the fillable PDF concept.

We considered adding this feature, but decided against it for the two reasons:
- The focus of SimplePDF is to fill forms, not to create fillable forms. There are plenty of alternatives that already do that, Adobe being one of them.
- Because not all fields would be made "fillable", the user experience would suffer: we prefer to stick to a simple yet consistent behaviour

I hope this makes sense!

**Comment by ashishjaddu** [comment]
If there's an easy way for me to make them fillable, could you help me?
True that there are number of alternatives but
I saw a number of alternatives which are doing the same but they aren't as easy as SimplePDF to use. Their easy of use is not so easy and also they are charging insane prices just to provide fillable form fields in the form.
